services:
  - type: web
    name: fraudshield-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SECRET_KEY
        value: your-secret-key-here-change-in-production
      - key: REDIS_URL
        value: redis://red-xyz123.render.com:6379